type Mutation {
  updateUserName(
    firstName: String!
    lastName: String!
    currentPassword: String!
  ): UpdateUserNameResponse!
}

union UpdateUserNameResponse =
    TokenError
  | UpdateUserNameCredentialError
  | UpdateUserNameSuccessResponse
  | UpdateUserInvalidUserCredentialError

type UpdateUserNameSuccessResponse {
  firstName: String!
  lastName: String!
}

enum UpdateUserNameCredentialField {
  currentPassword
  firstName
  lastName
}

type UpdateUserNameCredentialError implements Error {
  field: UpdateUserNameCredentialField
  message: String!
}

input ToUpdateName {
  firstName: String!
  lastName: String!
}
