type Mutation {
  updateUserName(firstName: String!, lastName: String!): UpdateUserNameResponse!
}

union UpdateUserNameResponse =
    TokenError
  | UpdateUserNameArgsError
  | UpdateUserNameSuccessResponse

type UpdateUserNameSuccessResponse {
  firstName: String!
  lastName: String!
}

enum UpdateUserNameArgsField {
  firstName
  lastName
}

type UpdateUserNameArgsError implements Error {
  field: UpdateUserNameArgsField
  message: String!
}

input ToUpdateName {
  firstName: String!
  lastName: String!
}
