type Mutation {
  removeUserPicture: RemoveUserPictureResponse!
}

union RemoveUserPictureResponse = TokenError | RemoveUserPictureSuccessResponse

type RemoveUserPictureSuccessResponse {
  picture: String!
}
