type User {
  name: String!
  email: String!
}

type ErrorResponse {
  title: String!
  message: String!
}

type SuccessResponse {
  message: String!
}

type AccessToken {
  token: String!
}

union UserInfo = User | ErrorResponse
union DeleteData = SuccessResponse | ErrorResponse
