type Mutation {
  createUser(
    firstName: String!
    lastName: String!
    email: String!
    password: String!
  ): CreateUserResponse!
}

union CreateUserResponse =
    Token
  | CreateUserCredentialError
  | UserAlreadyExistError

type CreateUserCredentialError implements Error {
  message: String!
  field: CreateUserCredentialFiled!
}

enum CreateUserCredentialFiled {
  firstName
  lastName
  email
  password
}

type UserAlreadyExistError implements Error {
  message: String!
}
