type Mutation {
  createUser(
    firstName: String!
    lastName: String!
    email: String!
    password: String!
  ): CreateUserResponse!
}

union CreateUserResponse = Token | CreateUserArgsError | UserAlreadyExistError

type CreateUserArgsError implements Error {
  message: String!
  field: CreateUserArgsFiled!
}

enum CreateUserArgsFiled {
  firstName
  lastName
  email
  password
}

type UserAlreadyExistError implements Error {
  message: String!
}
