type Mutation {
  updateUserPicture(picture: String!): UpdateUserPictureResponse!
}

union UpdateUserPictureResponse =
    TokenError
  | UpdateUserPictureArgsError
  | UpdateUserPictureSuccessResponse
  | InvalidCredentialError

type UpdateUserPictureSuccessResponse {
  picture: String!
}

enum UpdateUserPictureField {
  picture
}

type UpdateUserPictureArgsError implements Error {
  field: UpdateUserPictureField!
  message: String!
}

type InvalidCredentialError implements Error {
  message: String!
}
