type Mutation {
  updateUserPicture(picture: String!): UpdateUserPictureResponse!
}

union UpdateUserPictureResponse =
    TokenError
  | UpdateUserPictureArgsError
  | UpdateUserPictureSuccessResponse

type UpdateUserPictureSuccessResponse {
  picture: String!
}

enum UpdateUserPictureField {
  picture
}

type UpdateUserInvalidUserArgsError implements Error {
  field: UpdateUserPictureField!
  message: String!
}
