type Mutation {
  updateUserPicture(file: String!): UpdateUserPictureResponse!
}

union UpdateUserPictureResponse =
    TokenError
  | UpdateUserPictureCredentialError
  | UpdateUserPictureSuccessResponse

type UpdateUserPictureSuccessResponse {
  picture: String!
}

type UpdateUserPictureCredentialError implements Error {
  message: String!
}

type UpdateUserInvalidUserCredentialError implements Error {
  message: String!
}
