type Query {
  readProduct(
    category: String!
    pagination: Int!
    isPublic: Boolean!
  ): ProductInfo
}

type Mutation {
  createProduct(
    name: String!
    description: String!
    isPublic: Boolean!
  ): ProductInfo
  updateProduct(
    id: String!
    toUpdate: String!
    name: String
    description: String
    isPublic: Boolean
  ): ProductInfo
  deleteProduct(id: String!): DeleteData
}

type Product {
  name: String!
  description: String!
  isPublic: String!
  seller: Seller!
}

type Seller {
  id: String!
  name: String!
}

union ProductInfo = Product | ErrorResponse
