type Query {
  readProduct(
    category: String!
    isPublic: Boolean!
    skip: Int!
    limit: Int!
  ): [ProductInfo]
}

type Mutation {
  createProduct(
    name: String!
    description: String!
    isPublic: Boolean!
    category: String!
  ): ProductInfo
  updateProduct(
    id: String!
    toUpdate: String!
    name: String
    description: String
    isPublic: Boolean
  ): ProductInfo
  deleteProduct(id: String!): Response
}

type Product {
  id: String!
  name: String!
  description: String!
  isPublic: Boolean!
  category: String!
}

union ProductInfo = Product | ErrorResponse
