type User {
  firstName: String!
  lastName: String!
  email: String!
  picture: String!
}

type ErrorResponse {
  title: String!
  message: String!
}

type SuccessResponse {
  message: String!
}

type AccessToken {
  token: String!
}

union UserInfo = User | ErrorResponse
union Response = SuccessResponse | ErrorResponse
