type Mutation {
  createSession(email: String!, password: String!): CreateSessionResponse!
  deleteSession: DeleteSessionResponse!
  deleteAllSession(currentPassword: String!): DeleteAllSessionResponse!
}

union CreateSessionResponse = CreateSessionCredentialError | Token
union DeleteSessionResponse = SuccessResponse | TokenError
union DeleteAllSessionResponse =
    SuccessResponse
  | DeleteAllSessionCredentialError
  | TokenError

type CreateSessionCredentialError implements Error {
  message: String!
}

type DeleteAllSessionCredentialError implements Error {
  message: String!
}
