type Mutation {
  createSession(email: String!, password: String!): CreateSessionResponse!
  updateSession: Response
  deleteSession: DeleteSessionResponse!
  deleteAllSession(currentPassword: String!): Response
}

type CreateSessionCredentialError implements Error {
  message: String!
}

type LogoutSuccess {
  message: String!
}

union CreateSessionResponse = CreateSessionCredentialError | Token
union DeleteSessionResponse = LogoutSuccess | TokenError
