type Query {
  readUser: UserInfo
}

type Mutation {
  createUser(
    firstName: String!
    lastName: String!
    email: String!
    password: String!
  ): TokenResponse
  deleteUser(currentPassword: String!): Response
  updateUser(
    toUpdate: String!
    email: String
    password: String
    name: FullName
    currentPassword: String!
  ): UserInfo
}

input FullName {
  firstName: String
  lastName: String
}

type Token {
  token: String!
}

union TokenResponse = Token | ErrorResponse
