type Mutation {
  updateUserPassword(
    currentPassword: String!
    password: String!
  ): UpdateUserPasswordResponse!
}

union UpdateUserPasswordResponse =
    TokenError
  | UpdateUserPasswordCredentialError
  | UpdateUserPasswordSuccessResponse
  | UpdateUserInvalidUserCredentialError

type UpdateUserPasswordSuccessResponse {
  message: String!
}

enum UpdateUserPasswordCredentialField {
  currentPassword
  password
}

type UpdateUserPasswordCredentialError implements Error {
  field: UpdateUserPasswordCredentialField
  message: String!
}
