type Mutation {
  updateUserPassword(
    currentPassword: String!
    password: String!
  ): UpdateUserPasswordResponse!
}

union UpdateUserPasswordResponse =
    TokenError
  | SuccessResponse
  | UpdateUserPasswordArgsError
  | InvalidCredentialError

enum UpdateUserPasswordField {
  currentPassword
  password
}

type UpdateUserPasswordArgsError implements Error {
  field: UpdateUserPasswordField!
  message: String!
}

enum UpdateUserPasswordCredentialField {
  currentPassword
}

type InvalidCredentialError implements Error {
  message: String!
}
