type CreateUser {
  name: String
  email: String
}

type GetUser {
  name: String
  email: String
}

type Response {
  message: String
  status: String
}

type Query {
  readUser: GetUser
}

type Error {
  message: String!
}

union CreateUserResponse = CreateUser | Error

type Mutation {
  createUser(
    name: String!
    email: String!
    password: String
  ): CreateUserResponse

  deleteUser(currentPassword: String): Response

  updateUser(
    toUpdate: String!
    email: String
    password: String
    name: String
    currentPassword: String
  ): CreateUser
}
