type Mutation {
  deleteUser(currentPassword: String!): DeleteUserResponse!
}

union DeleteUserResponse =
    SuccessResponse
  | TokenError
  | DeleteUserArgsError
  | DeleteUserCredentialError

type DeleteUserArgsError implements Error {
  field: DeleteUserArgsField!
  message: String!
}

enum DeleteUserArgsField {
  currentPassword
}

type DeleteUserCredentialError implements Error {
  field: DeleteUserArgsField!
  message: String!
}
