type Mutation {
  updateUserEmail(
    email: String!
    currentPassword: String!
  ): UpdateUserEmailResponse!
}

union UpdateUserEmailResponse =
    TokenError
  | UserAlreadyExistError
  | UpdateUserEmailArgsError
  | UpdateUserEmailSuccessResponse

enum UpdateUserEmailField {
  email
}

type UpdateUserEmailArgsError implements Error {
  field: UpdateUserEmailField!
  message: String!
}

type UpdateUserEmailSuccessResponse {
  email: String!
}
